### ISSUE TITLE
Add auto-updating system

### ISSUE THREAD

**Issue by ijsKoud** [ijsKoud/PaperPlane#79]
Not sure if this is ever going to work but I would be cool to add. Saves a lot of ssh login time

**Comment by DaanGamesDG** [comment]
Fixed with version [v3.0.0](https://github.com/DaanGamesDG/PaperPlane/tree/chore-release/v3) (branch will change to main eventually when everything for v3 is done).

*note: only available when using Docker: [WatchTower](https://containrrr.dev/watchtower/)*

**Comment by ijsKoud** [comment]
Resolved: https://paperplane.ijskoud.dev/docs/get-started#optional-enable-autoupdating
