### ISSUE TITLE
Add landing page

### ISSUE THREAD

**Issue by ijsKoud** [ijsKoud/PaperPlane#80]
Right now, you get redirected to repo when you visit the index route. At first I thought it wouldn't be annoying but I was completely wrong and I keep forgetting about it.

Make a landing page that allows you to visit the dashboard or get to the repo

**Comment by rolkoztm** [comment]
yes do it

**Comment by DaanGamesDG** [comment]
Fixed with version [v3.0.0](https://github.com/DaanGamesDG/PaperPlane/tree/chore-release/v3) (branch will change to main eventually when everything for v3 is done)
